# Generated by Django 3.1.5 on 2021-02-19 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entry', '0010_auto_20210219_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_without_vat', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='不含税额')),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='税额')),
                ('invoice_number', models.CharField(max_length=8, verbose_name='发票号码')),
                ('send', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='entry.entry')),
            ],
            options={
                'verbose_name': '增值税发票',
                'verbose_name_plural': '增值税发票',
                'ordering': ['created'],
            },
        ),
    ]
