# Generated by Django 3.1.5 on 2021-02-02 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('address', models.CharField(max_length=255, verbose_name='项目地址')),
                ('manager', models.CharField(max_length=255, verbose_name='项目经理')),
                ('active', models.BooleanField(default=True, verbose_name='有效')),
                ('text', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='启动时间')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='竣工时间')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFinanceInitialDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accumulated_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='累计确认收入')),
                ('accumulated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='累计确认成本')),
                ('capitalized_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='合同履约成本')),
                ('contract_asset', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='合同资产')),
                ('contract_liability', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='合同负债')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='合同取得成本')),
                ('accumulated_cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='累计收款')),
                ('accumulated_cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='累计付款')),
                ('accounts_receivable_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='应收账款')),
                ('accounts_payable_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='应付账款')),
                ('accounts_prepaid_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='预付分包款')),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='销项税金')),
                ('vat_input', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='进项税金')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='projects.project')),
            ],
            options={
                'verbose_name': '项目初始财务情况',
                'verbose_name_plural': '项目初始财务情况',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(max_length=255, verbose_name='名称')),
                ('target_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='目标收入')),
                ('target_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='目标成本')),
                ('target_profit', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='目标利润')),
                ('target_expense', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='管理费用')),
                ('description', models.TextField(blank=True, null=True, verbose_name='变更说明')),
                ('change_time', models.DateTimeField(blank=True, null=True, verbose_name='变更时间')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='projects.project')),
            ],
            options={
                'verbose_name': '项目预算',
                'verbose_name_plural': '项目预算',
                'ordering': ['created'],
            },
        ),
    ]
