# Generated by Django 3.1.2 on 2021-01-19 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('address', models.CharField(max_length=255, verbose_name='项目地址')),
                ('manager', models.CharField(max_length=255, verbose_name='项目经理')),
                ('active', models.BooleanField(default=True, verbose_name='有效')),
                ('text', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFinanceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accumulated_revenue', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='累计确认收入')),
                ('accumulated_cost', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='累计确认成本')),
                ('capitalized_cost', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='合同履约成本余额')),
                ('contract_liability', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='合同负债余额')),
                ('contract_asset', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='合同资产余额')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='合同取得成本余额')),
                ('accumulated_cash_in', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='累计收合同款')),
                ('accumulated_cash_out', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='累计付合同款')),
                ('accounts_receivable_balance', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='应收账款余额')),
                ('accounts_payable_balance', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='应付账款')),
                ('vat', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='销项税金')),
                ('vat_input', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='进项税金')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.project')),
            ],
        ),
    ]
