# Generated by Django 3.1.2 on 2021-01-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectFinanceDetail',
            new_name='ProjectFinanceInitialDetail',
        ),
    ]
