# Generated by Django 3.1.2 on 2021-01-19 21:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210119_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfinanceinitialdetail',
            options={'ordering': ['-created'], 'verbose_name': '项目初始财务情况', 'verbose_name_plural': '项目初始财务情况'},
        ),
        migrations.AddField(
            model_name='projectfinanceinitialdetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectfinanceinitialdetail',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='projectfinanceinitialdetail',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='projects.project'),
        ),
    ]
