# Generated by Django 3.1.5 on 2021-02-02 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.IntegerField(choices=[(1, '收入合同'), (2, '成本合同'), (3, '其他合同'), (4, '非合同')], primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=4, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '合同类型',
                'verbose_name_plural': '合同类型',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='印花税类型')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='印花税税率')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '印花税',
                'verbose_name_plural': '印花税',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=255, unique=True, verbose_name='合同编号')),
                ('contract_name', models.CharField(max_length=255, verbose_name='合同名称')),
                ('contract_price', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='合同含税总价')),
                ('contract_date', models.DateTimeField(blank=True, null=True, verbose_name='签订日期')),
                ('contract_end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束日期')),
                ('contract_detail', models.CharField(max_length=255, verbose_name='合同标的')),
                ('contract_primary', models.CharField(max_length=255, verbose_name='主要合同对手')),
                ('contract_secondary1', models.CharField(blank=True, max_length=255, null=True, verbose_name='其他合同对手1')),
                ('contract_secondary2', models.CharField(blank=True, max_length=255, null=True, verbose_name='其他合同对手2')),
                ('contract_secondary3', models.CharField(blank=True, max_length=255, null=True, verbose_name='其他合同对手3')),
                ('contract_text', models.TextField(blank=True, null=True, verbose_name='支付条款')),
                ('contract_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系人')),
                ('contract_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系电话')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('contract_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='projects.project', verbose_name='项目名称')),
                ('contract_stamp_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stamp', to='contracts.stamp', verbose_name='合同类别')),
                ('contract_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_type', to='contracts.contracttype', verbose_name='合同类型')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同',
                'ordering': ['created'],
            },
        ),
    ]
