# Generated by Django 3.1.2 on 2021-01-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contracttype',
            old_name='name',
            new_name='type_id',
        ),
    ]
