# Generated by Django 3.1.2 on 2021-01-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20210121_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracttype',
            name='type_id',
        ),
        migrations.AddField(
            model_name='contracttype',
            name='name',
            field=models.CharField(default=1, max_length=4, verbose_name='类型名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='id',
            field=models.IntegerField(choices=[(1, '收入合同'), (2, '成本合同'), (3, '其他合同')], primary_key=True, serialize=False),
        ),
    ]
