# Generated by Django 3.1.2 on 2021-01-21 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20210121_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracttype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='contracttype',
            name='updated',
        ),
    ]
