# Generated by Django 3.1.2 on 2021-01-30 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210121_2145'),
        ('contracts', '0004_auto_20210121_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttype',
            name='id',
            field=models.IntegerField(choices=[(1, '收入合同'), (2, '成本合同'), (3, '其他合同'), (4, '非合同')], primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=255, unique=True, verbose_name='合同编号')),
                ('contract_name', models.CharField(max_length=255, verbose_name='合同名称')),
                ('contract_price', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='合同含税总价')),
                ('contract_date', models.DateTimeField(blank=True, null=True, verbose_name='签订日期')),
                ('contract_end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束日期')),
                ('contract_stamp_type', models.CharField(max_length=255, verbose_name='合同类型')),
                ('contract_detail', models.CharField(max_length=255, verbose_name='合同标的')),
                ('contract_primary', models.CharField(max_length=255, verbose_name='主要合同对手')),
                ('contract_secondary1', models.CharField(blank=True, max_length=255, null=True, verbose_name='其他合同对手1')),
                ('contract_secondary2', models.CharField(blank=True, max_length=255, null=True, verbose_name='其他合同对手2')),
                ('contract_secondary3', models.CharField(blank=True, max_length=255, null=True, verbose_name='其他合同对手3')),
                ('contract_text', models.TextField(blank=True, null=True, verbose_name='支付条款')),
                ('contract_contactor', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系人')),
                ('contract_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系电话')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('contract_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='projects.project', verbose_name='项目名称')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_type', to='contracts.contracttype', verbose_name='合同类型')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同',
                'ordering': ['-created'],
            },
        ),
    ]
