# Generated by Django 3.1.5 on 2021-02-04 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settlements', '0003_auto_20210202_1407'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accumulated_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='累计确认收入')),
                ('accumulated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='累计确认成本')),
                ('capitalized_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='合同履约成本')),
                ('contract_asset', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='合同资产')),
                ('contract_liability', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='合同负债')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='合同取得成本')),
                ('accumulated_cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='累计收款')),
                ('accumulated_cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='累计付款')),
                ('accounts_receivable_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='应收账款')),
                ('accounts_payable_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='应付账款')),
                ('accounts_prepaid_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='预付分包款')),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='销项税金')),
                ('vat_input', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='进项税金')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='货币资金')),
                ('others_asset', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='其他资产')),
                ('others_liability', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='其他负债')),
                ('others_profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='其他损益')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_entries', to='projects.project', verbose_name='关联合同')),
                ('income_settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_entries', to='settlements.incomesettlement', verbose_name='关联收款结算')),
                ('payment_settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_entries', to='settlements.paymentsettlement', verbose_name='关联付款结算')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_entries', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '变动记录',
                'verbose_name_plural': '变动记录',
                'ordering': ['created'],
            },
        ),
    ]
