# Generated by Django 3.1.5 on 2021-02-04 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0003_auto_20210202_1407'),
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='income_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_entries', to='settlements.incomesettlement', verbose_name='关联收款结算'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='payment_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_entries', to='settlements.paymentsettlement', verbose_name='关联付款结算'),
        ),
    ]
