# Generated by Django 3.1.5 on 2021-02-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20210204_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='变动描述'),
        ),
    ]
