# Generated by Django 3.1.5 on 2021-02-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_costtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostType',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='accumulated_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='accumulated_revenue',
            new_name='revenue',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='accumulated_cash_in',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='accumulated_cash_out',
        ),
        migrations.AddField(
            model_name='entry',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='变动描述'),
        ),
    ]
