# Generated by Django 3.1.5 on 2021-02-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_auto_20210205_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='accounts_payable_balance',
            new_name='accounts_payable',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='accounts_prepaid_balance',
            new_name='accounts_prepaid',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='accounts_receivable_balance',
            new_name='accounts_receivable',
        ),
    ]
