# Generated by Django 3.1.5 on 2021-02-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0008_auto_20210207_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='确认成本'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='确认收入'),
        ),
    ]
