# Generated by Django 3.1.2 on 2021-01-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-created'], 'verbose_name': '更新记录', 'verbose_name_plural': '更新记录'},
        ),
    ]
