# Generated by Django 3.1.2 on 2021-02-01 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_auto_20210201_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settle_prepayment', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='应结算款-预付款项')),
                ('settle_design', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='应结算款-设计服务')),
                ('settle_management', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='应结算款-管理服务')),
                ('settle_material', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='应结算款-材料销售')),
                ('settle_construction', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='应结算款-工程服务')),
                ('deduction_prepayment', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='扣款-预付款项')),
                ('deduction_warranty', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='扣款-质保金')),
                ('deduction_damage', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='扣款-违约金')),
                ('deduction_other', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='扣款-其他扣款')),
                ('received_prepayment', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='实际收款-预收款')),
                ('received_normal', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='实际收款-进度款')),
                ('received_warranty', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='实际收款-质保金')),
                ('received_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='实际收款-奖励款')),
                ('received_other', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='实际收款-其他')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='contracts.contract', verbose_name='结算记录')),
            ],
            options={
                'verbose_name': '结算记录',
                'verbose_name_plural': '结算记录',
                'ordering': ['created'],
            },
        ),
    ]
