# Generated by Django 3.1.5 on 2021-02-02 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomesettlement',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='contracts.contract', verbose_name='结算记录-收入'),
        ),
        migrations.AlterField(
            model_name='incomesettlement',
            name='settle_construction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='应收结算款-工程服务'),
        ),
        migrations.AlterField(
            model_name='incomesettlement',
            name='settle_design',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='应收结算款-设计服务'),
        ),
        migrations.AlterField(
            model_name='incomesettlement',
            name='settle_management',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='应收结算款-管理服务'),
        ),
        migrations.AlterField(
            model_name='incomesettlement',
            name='settle_material',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='应收结算款-材料销售'),
        ),
        migrations.AlterField(
            model_name='incomesettlement',
            name='settle_prepayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='应收结算款-预付款项'),
        ),
        migrations.CreateModel(
            name='PaymentSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='结算说明')),
                ('payment_prepaid', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='应付结算款-预付款项')),
                ('payment_normal', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='应付结算款-合同款')),
                ('payment_other', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='应付结算款-其他')),
                ('deduction_prepayment', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='扣款-预付款项')),
                ('deduction_warranty', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='扣款-质保金')),
                ('deduction_damage', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='扣款-违约金')),
                ('deduction_other', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='扣款-其他扣款')),
                ('payment_real_construction', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='实际付款-工程分包款')),
                ('payment_real_equipment', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='实际付款-设备款')),
                ('payment_real_material', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='实际付款-材料款')),
                ('payment_real_rent', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='实际付款-租赁款')),
                ('payment_real_design', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='实际付款-设计费')),
                ('payment_real_other', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='实际付款-其他')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_payment', to='contracts.contract', verbose_name='结算记录-支出')),
            ],
            options={
                'verbose_name': '结算记录-支付',
                'verbose_name_plural': '结算记录-支付',
                'ordering': ['created'],
            },
        ),
    ]
