# Generated by Django 3.1.5 on 2021-02-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0002_auto_20210202_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsettlement',
            name='payment_real_construction',
        ),
        migrations.RemoveField(
            model_name='paymentsettlement',
            name='payment_real_equipment',
        ),
        migrations.AddField(
            model_name='paymentsettlement',
            name='payment_real_normal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='实际付款-工程款'),
        ),
        migrations.AddField(
            model_name='paymentsettlement',
            name='payment_real_prepaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='实际付款-预付款'),
        ),
    ]
